#!/usr/bin/env php
<?php
/**
 * Created by PhpStorm.
 * User: marcfsr
 * Date: 11/03/2019
 * Time: 19:17
 */
include_once __DIR__ . "/../vendor/autoload.php";

echo str_color("Now compiling client side views...", "f_yellow") . PHP_EOL;
new \CloudsDotEarth\Bundles\Core\ViewCompiler
(
    [__DIR__ . "/../src/client/views"],
    __DIR__ . "/../generated/views"
);
echo str_color("Compilation done.", "f_green") . PHP_EOL;